# basic
title: dev4mobile 
subtitle: Coding is my life 
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: 
# banner_large: images/banner-large.png
avatar: images/avatar.png
banner_small: images/banner-small.png
banner_large: images/banner-large.png 

# disqus
disqus_shortname: dev4mobile

# social
social:
  github: https://github.com/dev4mobile
  twitter: https://twitter.com/dev4mobiles
  weibo: http://weibo.com/6251708754

# nav #
nav:
  home: .
  archive: archives
  # about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


google_analytics: # Put tracking ID here
