# basic
title: dev4mobile 
subtitle: Coding is my life 
favicon: favicon.ico

# avatar: images/avatar.png
# banner_small: images/banner-small.png
# banner_large: images/banner-large.png
avatar: images/avatar.png
banner_small: http://www.shuoshuokong.com/uploads/allimg/170613/1-1F613160U1.jpg
banner_large: http://img95.699pic.com/photo/50055/5642.jpg_wh300.jpg

# disqus
disqus_shortname: dev4mobile

# social
social:
  github: https://github.com/dev4mobile
  twitter: https://twitter.com/dev4mobiles
  weibo: http://weibo.com/cha12chalyc

# nav #
nav:
  home: .
  archive: archives
  # about: about
  rss: atom.xml

# heox-renderre-sass
node_sass:
  outputStyle: nested
  precision: 5
  sourceComments: false


google_analytics: # Put tracking ID here
